In [1]:
import numpy as np
import torch

import torch.nn as nn
import torch.nn.init as init


# Tensor Initializations

In [6]:

device= "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
# making tensors

my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
torch.float32
cuda:0
torch.Size([2, 3])
False


In [13]:
# zeros

x=torch.zeros((3,3),dtype=torch.float32,device=device)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
tensor([[0.8889, 0.0930, 0.6336],
        [0.1215, 0.2709, 0.4494],
        [0.7726, 0.1277, 0.5587]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0')


In [ ]:

# rand is uniform distribution from 0 to 1
x=torch.rand((3,3),dtype=torch.float32,device=device)
print(x)


In [ ]:

x=torch.ones((3,3),dtype=torch.float32,device=device)
print(x)


In [ ]:

# I-dentity matrix
x=torch.eye(5,5,dtype=torch.float32,device=device)
print(x)

In [15]:
#makes an array from start to end with a step size
x=torch.arange(start=0,end=5,step=1,dtype=torch.float32,device=device)
print(x)

tensor([0., 1., 2., 3., 4.], device='cuda:0')


In [17]:
# linspace is like arange but it makes a number of points

x=torch.linspace(start=0.1,end=1,steps=10,dtype=torch.float32,device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [26]:
# diag
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32, device=device)
print(x)

# if diag takes a 2d tensor it returns the diagonal
y=torch.diag(x)
print(y)

# if diag takes a 1d tensor it returns a 2d tensor with the diagonal being the 1d tensor
y=torch.diag(x[1])
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')
tensor([1., 5., 9.], device='cuda:0')
tensor([[4., 0., 0.],
        [0., 5., 0.],
        [0., 0., 6.]], device='cuda:0')


In [33]:
# numpy array to gpu tensor
np_array=np.zeros((5,5))
my_tensor=torch.from_numpy(np_array).float().to(device)
print(my_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')


# Math Operations