In [1]:
import numpy as np
import torch

import torch.nn as nn
import torch.nn.init as init


# Tensor Initializations

In [2]:

device= "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
# making tensors

my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
torch.float32
cuda:0
torch.Size([2, 3])
False


In [4]:
# zeros

x=torch.zeros((3,3),dtype=torch.float32,device=device)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [5]:

# rand is uniform distribution from 0 to 1
x=torch.rand((3,3),dtype=torch.float32,device=device)
print(x)


tensor([[0.3552, 0.8622, 0.6864],
        [0.2183, 0.6978, 0.7925],
        [0.7819, 0.9810, 0.4143]], device='cuda:0')


In [6]:

x=torch.ones((3,3),dtype=torch.float32,device=device)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [7]:

# I-dentity matrix
x=torch.eye(5,5,dtype=torch.float32,device=device)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0')


In [14]:
#makes an array from start to end with a step size
x=torch.arange(start=0,end=5,step=1,dtype=torch.float32,device=device)
print(x)

tensor([0., 1., 2., 3., 4.], device='cuda:0')


In [9]:
# linspace is like arange but it makes a number of points

x=torch.linspace(start=0.1,end=1,steps=10,dtype=torch.float32,device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [10]:
# diag
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32, device=device)
print(x)

# if diag takes a 2d tensor it returns the diagonal
y=torch.diag(x)
print(y)

# if diag takes a 1d tensor it returns a 2d tensor with the diagonal being the 1d tensor
y=torch.diag(x[1])
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')
tensor([1., 5., 9.], device='cuda:0')
tensor([[4., 0., 0.],
        [0., 5., 0.],
        [0., 0., 6.]], device='cuda:0')


In [11]:
# numpy array to gpu tensor
np_array=np.zeros((5,5))
my_tensor=torch.from_numpy(np_array).float().to(device)
print(my_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')


# Math Operations

In [16]:
first_Tensor=torch.rand((3,3),device=device)
second_Tensor=torch.rand((3,3),device=device)


tensor([[1.5118, 1.3778, 0.5977],
        [1.2791, 1.1519, 0.6623],
        [1.0835, 0.4510, 0.8564]], device='cuda:0')
tensor([[-0.0777, -0.1710,  0.0704],
        [-0.4715,  0.6691, -0.3161],
        [ 0.8412, -0.0109, -0.6150]], device='cuda:0')
tensor([[0.5699, 0.4673, 0.0881],
        [0.3535, 0.2198, 0.0847],
        [0.1166, 0.0508, 0.0888]], device='cuda:0')
tensor([[1.1385, 0.7781, 0.7300],
        [1.1389, 0.5725, 0.6793],
        [0.9721, 0.8262, 0.4502]], device='cuda:0')


In [21]:

# element wise addition
print(first_Tensor+second_Tensor)

# element wise subtraction
print(first_Tensor-second_Tensor)

# element wise multiplication
print(first_Tensor*second_Tensor)

# matrix multiplication
print(first_Tensor.mm(second_Tensor))

# element wise power
print(first_Tensor**2)
# another method
print(first_Tensor.pow(2))
# mat power
print(first_Tensor.matrix_power(2))
print(first_Tensor.mm(first_Tensor))

tensor([[1.5118, 1.3778, 0.5977],
        [1.2791, 1.1519, 0.6623],
        [1.0835, 0.4510, 0.8564]], device='cuda:0')
tensor([[-0.0777, -0.1710,  0.0704],
        [-0.4715,  0.6691, -0.3161],
        [ 0.8412, -0.0109, -0.6150]], device='cuda:0')
tensor([[0.5699, 0.4673, 0.0881],
        [0.3535, 0.2198, 0.0847],
        [0.1166, 0.0508, 0.0888]], device='cuda:0')
tensor([[1.1385, 0.7781, 0.7300],
        [1.1389, 0.5725, 0.6793],
        [0.9721, 0.8262, 0.4502]], device='cuda:0')
tensor([[0.5142, 0.3641, 0.1116],
        [0.1631, 0.8291, 0.0300],
        [0.9262, 0.0484, 0.0146]], device='cuda:0')
tensor([[0.5142, 0.3641, 0.1116],
        [0.1631, 0.8291, 0.0300],
        [0.9262, 0.0484, 0.0146]], device='cuda:0')
tensor([[1.0793, 1.0556, 0.3843],
        [0.8239, 1.1108, 0.3134],
        [0.8951, 0.8076, 0.3742]], device='cuda:0')
tensor([[1.0793, 1.0556, 0.3843],
        [0.8239, 1.1108, 0.3134],
        [0.8951, 0.8076, 0.3742]], device='cuda:0')


In [28]:
#tensor from 1 to 9
from turtle import shape


x=torch.arange(1,10,dtype=torch.float32,device=device).reshape(3,3)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')


In [41]:
a,b=x.float().max(dim=1)
print(a,b)
z=torch.clamp(x,min=2,max=8)
print(z)

tensor([3., 6., 9.], device='cuda:0') tensor([2, 2, 2], device='cuda:0')
tensor([[2., 2., 3.],
        [4., 5., 6.],
        [7., 8., 8.]], device='cuda:0')


In [44]:
print(x[:,:1])

tensor([[1.],
        [4.],
        [7.]], device='cuda:0')


In [46]:
x=torch.tensor([1,0,1,1,1],device=device)

In [47]:
print(x)

tensor([1, 0, 1, 1, 1], device='cuda:0')
